---
name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install clang llvm pkg-config nettle-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: RUST_LOG=debug cargo test --workspace -- --nocapture
